-- 유저 생성
create user jsondual identified by jsondual default tablespace users quota unlimited on users;
grant connect, resource to jsondual;

-- 샘플 테이블, DV, JSON 데이터 구성 
DROP VIEW IF EXISTS team_dv;
DROP VIEW IF EXISTS race_dv;
DROP VIEW IF EXISTS driver_dv;
DROP TABLE IF EXISTS driver_race_map;
DROP TABLE IF EXISTS race;
DROP TABLE IF EXISTS driver;
DROP TABLE IF EXISTS team;

CREATE TABLE IF NOT EXISTS team
(team_id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
name    VARCHAR2(255) NOT NULL UNIQUE,
points  INTEGER NOT NULL,
CONSTRAINT team_pk PRIMARY KEY(team_id));

CREATE TABLE IF NOT EXISTS driver
(driver_id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
name      VARCHAR2(255) NOT NULL UNIQUE,
points    INTEGER NOT NULL,
team_id   INTEGER,
CONSTRAINT driver_pk PRIMARY KEY(driver_id),
CONSTRAINT driver_fk FOREIGN KEY(team_id) REFERENCES team(team_id));

CREATE TABLE IF NOT EXISTS race
(race_id   INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
name      VARCHAR2(255) NOT NULL UNIQUE,
laps      INTEGER NOT NULL,
race_date DATE,
podium  JSON,
CONSTRAINT   race_pk PRIMARY KEY(race_id));

CREATE TABLE IF NOT EXISTS driver_race_map
(driver_race_map_id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
race_id            INTEGER NOT NULL,
driver_id          INTEGER NOT NULL,
position           INTEGER,
CONSTRAINT driver_race_map_pk  PRIMARY KEY(driver_race_map_id),
CONSTRAINT driver_race_map_fk1 FOREIGN KEY(race_id) REFERENCES race(race_id),
CONSTRAINT driver_race_map_fk2 FOREIGN KEY(driver_id) REFERENCES driver(driver_id));

CREATE OR REPLACE TRIGGER driver_race_map_trigger
BEFORE INSERT ON driver_race_map
FOR EACH ROW
DECLARE
    v_points  INTEGER;
    v_team_id INTEGER;
BEGIN
SELECT team_id INTO v_team_id FROM driver WHERE driver_id = :NEW.driver_id;
IF :NEW.position = 1 THEN
    v_points := 25;
ELSIF :NEW.position = 2 THEN
    v_points := 18;
ELSIF :NEW.position = 3 THEN
    v_points := 15;
ELSIF :NEW.position = 4 THEN
    v_points := 12;
ELSIF :NEW.position = 5 THEN
    v_points := 10;
ELSIF :NEW.position = 6 THEN
    v_points := 8;
ELSIF :NEW.position = 7 THEN
    v_points := 6;
ELSIF :NEW.position = 8 THEN
    v_points := 4;
ELSIF :NEW.position = 9 THEN
    v_points := 2;
ELSIF :NEW.position = 10 THEN
    v_points := 1;
ELSE
    v_points := 0;
END IF;
UPDATE driver SET points = points + v_points
    WHERE driver_id = :NEW.driver_id;
UPDATE team SET points = points + v_points
    WHERE team_id = v_team_id;
END;
/

CREATE OR REPLACE JSON RELATIONAL DUALITY VIEW race_dv AS
SELECT JSON {
            '_id' IS r.race_id,
            'name'   IS r.name,
            'laps'   IS r.laps WITH NOUPDATE,
            'date'   IS r.race_date,
            'podium' IS r.podium WITH NOCHECK,
            'result' IS
                [ SELECT JSON {'driverRaceMapId' IS drm.driver_race_map_id,
                                'position'        IS drm.position,
                                UNNEST
                                (SELECT JSON {'driverId' IS d.driver_id,
                                                'name'     IS d.name}
                                    FROM driver d WITH NOINSERT UPDATE NODELETE
                                    WHERE d.driver_id = drm.driver_id)}
                    FROM driver_race_map drm WITH INSERT UPDATE DELETE
                    WHERE drm.race_id = r.race_id ]}
    FROM race r WITH INSERT UPDATE DELETE;
    
CREATE OR REPLACE JSON RELATIONAL DUALITY VIEW driver_dv AS
SELECT JSON {'_id' IS d.driver_id,
        'name'     IS d.name,
        'points'   IS d.points,
        UNNEST
            (SELECT JSON {'teamId' IS t.team_id,
                        'team'   IS t.name WITH NOCHECK}
                FROM team t WITH NOINSERT NOUPDATE NODELETE
                WHERE t.team_id = d.team_id),
        'race'     IS
            [ SELECT JSON {'driverRaceMapId' IS drm.driver_race_map_id,
                            UNNEST
                            (SELECT JSON {'raceId' IS r.race_id,
                                            'name'   IS r.name}
                                FROM race r WITH NOINSERT NOUPDATE NODELETE
                                WHERE r.race_id = drm.race_id),
                            'finalPosition'   IS drm.position}
                FROM driver_race_map drm WITH INSERT UPDATE NODELETE
                WHERE drm.driver_id = d.driver_id ]}
FROM driver d WITH INSERT UPDATE DELETE;

CREATE OR REPLACE JSON RELATIONAL DUALITY VIEW team_dv AS
SELECT JSON {'_id'  IS t.team_id,
            'name'    IS t.name,
            'points'  IS t.points,
            'driver'  IS
                [ SELECT JSON {'driverId' IS d.driver_id,
                                'name'     IS d.name,
                                'points'   IS d.points WITH NOCHECK}
                    FROM driver d WITH INSERT UPDATE
                    WHERE d.team_id = t.team_id ]}
    FROM team t WITH INSERT UPDATE DELETE;
    
INSERT INTO team_dv VALUES ('{"_id" : 301,
                        "name"   : "Red Bull",
                        "points" : 0,
                        "driver" : [ {"driverId" : 101,
                                        "name"     : "Max Verstappen",
                                        "points"   : 0},
                                    {"driverId" : 102,
                                        "name"     : "Sergio Perez",
                                        "points"   : 0} ]}');

INSERT INTO team_dv VALUES ('{"_id" : 302,
                            "name"   : "Ferrari",
                            "points" : 0,
                            "driver" : [ {"driverId" : 103,
                                            "name"     : "Charles Leclerc",
                                            "points"   : 0},
                                        {"driverId" : 104,
                                            "name"     : "Carlos Sainz Jr",
                                            "points"   : 0} ]}');

INSERT INTO team_dv VALUES ('{"_id" : 2,
                            "name"   : "Mercedes",
                            "points" : 0,
                            "driver" : [ {"driverId" : 105,
                                            "name"     : "George Russell",
                                            "points"   : 0},
                                        {"driverId" : 106,
                                            "name"     : "Lewis Hamilton",
                                            "points"   : 0} ]}');
COMMIT;    

INSERT INTO race_dv VALUES ('{"_id" : 201,
                            "name"   : "Bahrain Grand Prix",
                            "laps"   : 57,
                            "date"   : "2022-03-20T00:00:00",
                            "podium" : {}}');

INSERT INTO race_dv VALUES ('{"_id" : 202,
                            "name"   : "Saudi Arabian Grand Prix",
                            "laps"   : 50,
                            "date"   : "2022-03-27T00:00:00",
                            "podium" : {}}');

INSERT INTO race_dv VALUES ('{"_id" : 203,
                            "name"   : "Australian Grand Prix",
                            "laps"   : 58,
                            "date"   : "2022-04-09T00:00:00",
                            "podium" : {}}');
COMMIT;
